### ISSUE TITLE
Type 'Date' throws "Right-hand side of instanceOf is not callable"

### ISSUE THREAD

**Issue by joelmeiller** [sebakerckhof/faster-schema#1]
If I define a field like this
```
dateField: {
  type: Date,
}
```
I get the error "Right-hand side of instanceOf is not callable". If I remove the Date field (or replace it with String) the validation works again.

Do I define the field incorrectly or is it a bug?

**Comment by sebakerckhof** [comment]
Can you create a reproduction?

Here it seems to work correct:
https://runkit.com/sebakerckhof/faster-schema-date-example

**Comment by joelmeiller** [comment]
Hi there, thanks for your reply. This was my mistake as I forgot to migrate one of the embedded schemas from simple-schema to faster-schema. I close the issue.
